# This line specifies the name of the library in which all the object
# files for the sources below will be collected into.
LIBRARY = libbase.a

# This line specifies the source files that will becompiled to form
# the library
SOURCES = \
	main.cpp \
	Module.cpp \
	ModuleManager.cpp \
	Tokenizer.cpp \
	SymbolTable.cpp \
    Floats.cpp \
    Strings.cpp 

# This line specifies any additional flags that you want to feed the
# compiler. It is usually used to specify additional include
# directories through -I and additional link directories through -L
AUXFLAGS = 

#################################################
# The rest of this file should not be modified  #
#################################################

include ../tools/libtargets.mk
